<?php

namespace Nails\MFA\Driver\Authentication;

use BaconQrCode\Renderer\Image\SvgImageBackEnd;
use BaconQrCode\Renderer\ImageRenderer;
use BaconQrCode\Renderer\RendererStyle\RendererStyle;
use BaconQrCode\Writer;
use Nails\Auth\Resource\User;
use Nails\Common\Driver\Base;
use Nails\Common\Service\UserFeedback;
use Nails\Config;
use Nails\Factory;
use Nails\MFA\Constants;
use Nails\MFA\Driver\Authentication\Authenticator\Settings\Settings;
use Nails\MFA\Driver\Authentication\Authenticator\SystemClock;
use Nails\MFA\Exception\InvalidCodeException;
use Nails\MFA\Exception\MfaException;
use Nails\MFA\Interfaces\Authentication\Driver;
use Nails\MFA\Resource\Token;
use Nails\MFA\Resource\UserMethod;
use Nails\MFA\Service\MultiFactorAuth;
use OTPHP\TOTP;
use stdClass;
use Throwable;

class Authenticator extends Base implements Driver
{
    public function getLabel(): string
    {
        return 'Authenticator';
    }

    // --------------------------------------------------------------------------

    public function getDescription(): string
    {
        return 'Allows a user to enter a code generated by their authenticator app.';
    }

    // --------------------------------------------------------------------------

    public function getSetupDescription(): string
    {
        return 'Use an authenticator app on your phone to generate a verification code when you sign in.';
    }

    // --------------------------------------------------------------------------

    public function isEnabled(): bool
    {
        return true;
    }

    // --------------------------------------------------------------------------

    public function preForm(Token $oToken, UserFeedback $oUserFeedback): void
    {
        $oUserFeedback->success(
            $this->getSetting(Settings::KEY_FEEDBACK_PROMPT)
            ?: 'Enter the code from your authenticator app.'
        );
    }

    // --------------------------------------------------------------------------

    public function postForm(Token $oToken): void
    {
        //  Not required
    }

    // --------------------------------------------------------------------------

    public function validate(Token $oToken, string $sCode): void
    {
        $oUser = $oToken->user();
        if (empty($oUser)) {
            throw new MfaException('Token is not associated with a user.');
        }

        /** @var MultiFactorAuth $oMfa */
        $oMfa    = Factory::service('MultiFactorAuth', Constants::MODULE_SLUG);
        $oMethod = $oMfa->getUserMethod($oUser, (string) $this->getSlug());
        if (!$oMethod) {
            throw new InvalidCodeException($this->invalidMessage());
        }

        $oData   = $oMethod->getDecodedData();
        $sSecret = (string) ($oData->secret ?? '');
        $iPeriod = static::matchingPeriod($sSecret, $sCode);

        if ($iPeriod === null) {
            throw new InvalidCodeException($this->invalidMessage());
        }

        if (isset($oData->last_period) && $iPeriod <= (int) $oData->last_period) {
            throw new InvalidCodeException($this->invalidMessage());
        }

        $oData->last_period = $iPeriod;
        $oMethod->setDecodedData($oData);
    }

    // --------------------------------------------------------------------------

    public function canTryAgain(): bool
    {
        return false;
    }

    // --------------------------------------------------------------------------

    public function resend(Token $oToken, UserFeedback $oUserFeedback): void
    {
        //  Codes come from the user's app, there is nothing to reissue
    }

    // --------------------------------------------------------------------------

    public function requiresEnrollment(): bool
    {
        return true;
    }

    // --------------------------------------------------------------------------

    public function setupStart(User $oUser): stdClass
    {
        //  RFC 4226 recommends a 160-bit shared secret
        $sSecret = TOTP::generate(clock: new SystemClock(), secretSize: 20)->getSecret();
        $sUri    = $this->otpAuthUri($oUser, $sSecret);

        return (object) [
            'secret'  => $sSecret,
            'otpauth' => $sUri,
            'qr_svg'  => static::qrSvg($sUri),
        ];
    }

    // --------------------------------------------------------------------------

    public function setupComplete(User $oUser, string $sCode, stdClass $oPending): stdClass
    {
        $sSecret = (string) ($oPending->secret ?? '');
        $iPeriod = static::matchingPeriod($sSecret, $sCode);

        if ($sSecret === '' || $iPeriod === null) {
            throw new InvalidCodeException($this->invalidMessage());
        }

        return (object) [
            'secret'       => $sSecret,
            'last_period'  => $iPeriod,
        ];
    }

    // --------------------------------------------------------------------------

    public function reset(User $oUser, UserMethod $oMethod): void
    {
        //  Secret lives on the method row and is deleted with it
    }

    // --------------------------------------------------------------------------

    public static function matchingPeriod(string $sSecret, string $sCode, int $iWindow = 1, ?int $iNow = null): ?int
    {
        $sCode = preg_replace('/\D/', '', $sCode) ?? '';
        if ($sSecret === '' || $sCode === '') {
            return null;
        }

        try {
            $oTotp  = TOTP::createFromSecret($sSecret, new SystemClock());
            $iNow   = $iNow ?? time();
            $iSlice = (int) floor($iNow / 30);

            for ($i = -$iWindow; $i <= $iWindow; $i++) {
                $iPeriod    = $iSlice + $i;
                $iTimestamp = $iPeriod * 30;
                if ($iTimestamp < 0) {
                    continue;
                }
                if (hash_equals($oTotp->at($iTimestamp), $sCode)) {
                    return $iPeriod;
                }
            }
        } catch (Throwable) {
            return null;
        }

        return null;
    }

    // --------------------------------------------------------------------------

    public static function qrSvg(string $sContent): string
    {
        $oRenderer = new ImageRenderer(
            new RendererStyle(200),
            new SvgImageBackEnd()
        );
        $oWriter   = new Writer($oRenderer);

        return $oWriter->writeString($sContent);
    }

    // --------------------------------------------------------------------------

    protected function otpAuthUri(User $oUser, string $sSecret): string
    {
        $sIssuer  = $this->getSetting(Settings::KEY_ISSUER);
        $sIssuer  = is_string($sIssuer) && $sIssuer !== ''
            ? $sIssuer
            : (string) (Config::get('APP_NAME') ?: 'Nails');
        $sAccount = (string) ($oUser->email ?: $oUser->username ?: $oUser->id);

        return sprintf(
            'otpauth://totp/%s:%s?secret=%s&issuer=%s&digits=6&period=30',
            rawurlencode($sIssuer),
            rawurlencode($sAccount),
            rawurlencode($sSecret),
            rawurlencode($sIssuer)
        );
    }

    // --------------------------------------------------------------------------

    protected function invalidMessage(): string
    {
        return $this->getSetting(Settings::KEY_FEEDBACK_INVALID)
            ?: 'Invalid code entered. Please try again.';
    }
}
